export const emojiData = [
    // Original emojis (50)
    { symbol: "🔥", name: "fire", keywords: ["hot", "burn", "flame"] },
    { symbol: "😂", name: "face with tears of joy", keywords: ["laugh", "funny", "joy"] },
    { symbol: "❤️", name: "red heart", keywords: ["love", "heart", "affection"] },
    { symbol: "🎯", name: "direct hit", keywords: ["target", "bullseye", "goal", "dart"] },
    { symbol: "💯", name: "hundred points", keywords: ["100", "perfect", "score"] },
    { symbol: "😍", name: "smiling face with heart-eyes", keywords: ["love", "heart", "crush"] },
    { symbol: "🙌", name: "raising hands", keywords: ["celebrate", "praise", "hooray"] },
    { symbol: "😊", name: "smiling face with smiling eyes", keywords: ["happy", "joy", "smile"] },
    { symbol: "👍", name: "thumbs up", keywords: ["approval", "like", "good"] },
    { symbol: "💀", name: "skull", keywords: ["dead", "funny", "LOL"] },
    { symbol: "🤔", name: "thinking face", keywords: ["hmm", "thoughtful", "question"] },
    { symbol: "🙏", name: "folded hands", keywords: ["please", "thank you", "pray"] },
    { symbol: "🎉", name: "party popper", keywords: ["celebration", "party", "fun"] },
    { symbol: "😎", name: "smiling face with sunglasses", keywords: ["cool", "chill", "confident"] },
    { symbol: "😢", name: "crying face", keywords: ["sad", "tears", "upset"] },
    { symbol: "🤯", name: "exploding head", keywords: ["mind blown", "shock", "wow"] },
    { symbol: "🥺", name: "pleading face", keywords: ["please", "cute", "sad"] },
    { symbol: "🎶", name: "musical notes", keywords: ["music", "song", "melody"] },
    { symbol: "🤩", name: "star-struck", keywords: ["excited", "amazed", "impressed"] },
    { symbol: "🚀", name: "rocket", keywords: ["space", "launch", "fast"] },
    { symbol: "🐶", name: "dog face", keywords: ["animal", "pet", "puppy"] },
    { symbol: "🌍", name: "globe with meridians", keywords: ["world", "earth", "global"] },
    { symbol: "📚", name: "books", keywords: ["library", "reading", "study"] },
    { symbol: "🏆", name: "trophy", keywords: ["award", "win", "champion"] },
    { symbol: "💪", name: "flexed biceps", keywords: ["strong", "fitness", "workout"] },
    { symbol: "👀", name: "eyes", keywords: ["look", "watch", "see"] },
    { symbol: "🍕", name: "pizza", keywords: ["food", "cheese", "yum"] },
    { symbol: "⚡", name: "high voltage", keywords: ["electric", "energy", "lightning"] },
    { symbol: "🌟", name: "glowing star", keywords: ["bright", "special", "shine"] },
    { symbol: "🎵", name: "musical note", keywords: ["music", "song", "melody"] },
    { symbol: "👑", name: "crown", keywords: ["royalty", "king", "queen"] },
    { symbol: "💔", name: "broken heart", keywords: ["sad", "love", "hurt"] },
    { symbol: "💡", name: "light bulb", keywords: ["idea", "innovation", "inspiration"] },
    { symbol: "🎤", name: "microphone", keywords: ["sing", "karaoke", "music"] },
    { symbol: "🏀", name: "basketball", keywords: ["sports", "game", "hoops"] },
    { symbol: "🚗", name: "car", keywords: ["vehicle", "drive", "road"] },
    { symbol: "✈️", name: "airplane", keywords: ["travel", "flight", "trip"] },
    { symbol: "🧠", name: "brain", keywords: ["smart", "intelligence", "mind"] },
    { symbol: "🕹️", name: "joystick", keywords: ["game", "play", "controller"] },
    { symbol: "📅", name: "calendar", keywords: ["date", "schedule", "event"] },
    { symbol: "🎭", name: "performing arts", keywords: ["drama", "theater", "acting"] },
    { symbol: "🥇", name: "1st place medal", keywords: ["win", "gold", "champion"] },
    { symbol: "📝", name: "memo", keywords: ["note", "writing", "document"] },
    { symbol: "🌈", name: "rainbow", keywords: ["color", "pride", "beautiful"] },
    { symbol: "🛒", name: "shopping cart", keywords: ["store", "buy", "grocery"] },
    { symbol: "🏡", name: "house", keywords: ["home", "building", "living"] },
    { symbol: "🍎", name: "red apple", keywords: ["fruit", "healthy", "food"] },
    { symbol: "🚦", name: "vertical traffic light", keywords: ["stop", "go", "road"] },
    { symbol: "🌺", name: "hibiscus", keywords: ["flower", "nature", "beautiful"] },
    { symbol: "🎂", name: "birthday cake", keywords: ["celebration", "party", "cake"] },
    { symbol: "📸", name: "camera", keywords: ["photo", "picture", "snapshot"] },
  
    // New emojis (100+)
    // Flags
    { symbol: "🇺🇸", name: "United States flag", keywords: ["USA", "American", "flag"] },
    { symbol: "🇬🇧", name: "United Kingdom flag", keywords: ["UK", "British", "flag"] },
    { symbol: "🇨🇦", name: "Canada flag", keywords: ["Canadian", "flag"] },
    { symbol: "🇦🇺", name: "Australia flag", keywords: ["Aussie", "flag"] },
    { symbol: "🇯🇵", name: "Japan flag", keywords: ["Japanese", "flag"] },
    { symbol: "🇫🇷", name: "France flag", keywords: ["French", "flag"] },
    { symbol: "🇩🇪", name: "Germany flag", keywords: ["German", "flag"] },
    { symbol: "🇮🇹", name: "Italy flag", keywords: ["Italian", "flag"] },
    { symbol: "🇧🇷", name: "Brazil flag", keywords: ["Brazilian", "flag"] },
    { symbol: "🇮🇳", name: "India flag", keywords: ["Indian", "flag"] },
    { symbol: "🇨🇳", name: "China flag", keywords: ["Chinese", "flag"] },
    { symbol: "🇰🇷", name: "South Korea flag", keywords: ["Korean", "flag"] },
    { symbol: "🇷🇺", name: "Russia flag", keywords: ["Russian", "flag"] },
    { symbol: "🇪🇸", name: "Spain flag", keywords: ["Spanish", "flag"] },
    { symbol: "🇲🇽", name: "Mexico flag", keywords: ["Mexican", "flag"] },
    
    // Sports
    { symbol: "⚽", name: "soccer ball", keywords: ["football", "sports"] },
    { symbol: "🏈", name: "american football", keywords: ["sports", "NFL"] },
    { symbol: "⚾", name: "baseball", keywords: ["sports", "MLB"] },
    { symbol: "🎾", name: "tennis", keywords: ["sports", "racket"] },
    { symbol: "🏐", name: "volleyball", keywords: ["sports", "game"] },
    { symbol: "🏉", name: "rugby football", keywords: ["sports", "ball"] },
    { symbol: "🎱", name: "pool 8 ball", keywords: ["billiards", "game"] },
    { symbol: "🏓", name: "ping pong", keywords: ["table tennis", "sports"] },
    { symbol: "🏸", name: "badminton", keywords: ["sports", "shuttlecock"] },
    { symbol: "🥊", name: "boxing glove", keywords: ["sports", "fight"] },
    { symbol: "🥋", name: "martial arts uniform", keywords: ["karate", "taekwondo"] },
    { symbol: "⛳", name: "flag in hole", keywords: ["golf", "sports"] },
    { symbol: "🏹", name: "bow and arrow", keywords: ["archery", "sports"] },
    { symbol: "🛹", name: "skateboard", keywords: ["skate", "sports"] },
    { symbol: "🛼", name: "roller skate", keywords: ["skating", "sports"] },
    { symbol: "🛷", name: "sled", keywords: ["winter", "sports"] },
    { symbol: "⛸️", name: "ice skate", keywords: ["skating", "winter"] },
    
    // Emotions
    { symbol: "😃", name: "grinning face with big eyes", keywords: ["happy", "joy", "excited"] },
    { symbol: "😄", name: "grinning face with smiling eyes", keywords: ["happy", "joy"] },
    { symbol: "😁", name: "beaming face with smiling eyes", keywords: ["happy", "excited"] },
    { symbol: "😆", name: "grinning squinting face", keywords: ["laugh", "happy"] },
    { symbol: "😅", name: "grinning face with sweat", keywords: ["hot", "happy"] },
    { symbol: "🤣", name: "rolling on the floor laughing", keywords: ["laugh", "funny"] },
    { symbol: "😇", name: "smiling face with halo", keywords: ["angel", "innocent"] },
    { symbol: "😉", name: "winking face", keywords: ["flirt", "joke"] },
    { symbol: "😌", name: "relieved face", keywords: ["peace", "relaxed"] },
    { symbol: "😋", name: "face savoring food", keywords: ["yummy", "tasty"] },
    { symbol: "😛", name: "face with tongue", keywords: ["playful", "silly"] },
    { symbol: "😜", name: "winking face with tongue", keywords: ["joke", "funny"] },
    { symbol: "🤪", name: "zany face", keywords: ["crazy", "silly"] },
    { symbol: "😝", name: "squinting face with tongue", keywords: ["crazy", "silly"] },
    { symbol: "🤑", name: "money-mouth face", keywords: ["rich", "money"] },
    { symbol: "🤗", name: "hugging face", keywords: ["hug", "love"] },
    { symbol: "🤭", name: "face with hand over mouth", keywords: ["shock", "surprise"] },
    { symbol: "🤫", name: "shushing face", keywords: ["quiet", "secret"] },
    { symbol: "🤥", name: "lying face", keywords: ["lie", "dishonest"] },
    { symbol: "😐", name: "neutral face", keywords: ["meh", "indifferent"] },
    { symbol: "😑", name: "expressionless face", keywords: ["blank", "unimpressed"] },
    { symbol: "😶", name: "face without mouth", keywords: ["silent", "speechless"] },
    { symbol: "😏", name: "smirking face", keywords: ["smug", "confident"] },
    { symbol: "😒", name: "unamused face", keywords: ["unhappy", "bored"] },
    { symbol: "🙄", name: "face with rolling eyes", keywords: ["sarcasm", "annoyed"] },
    { symbol: "😬", name: "grimacing face", keywords: ["awkward", "uncomfortable"] },
    { symbol: "🤤", name: "drooling face", keywords: ["hungry", "desire"] },
    { symbol: "😴", name: "sleeping face", keywords: ["tired", "sleep"] },
    { symbol: "😪", name: "sleepy face", keywords: ["tired", "sleep"] },
    { symbol: "😵", name: "dizzy face", keywords: ["confused", "woozy"] },
    { symbol: "🤐", name: "zipper-mouth face", keywords: ["silence", "secret"] },
    { symbol: "🤢", name: "nauseated face", keywords: ["sick", "ill"] },
    { symbol: "🤮", name: "face vomiting", keywords: ["sick", "ill"] },
    { symbol: "🤧", name: "sneezing face", keywords: ["sick", "allergy"] },
    { symbol: "🥵", name: "hot face", keywords: ["heat", "fever"] },
    { symbol: "🥶", name: "cold face", keywords: ["freezing", "chilly"] },
    { symbol: "🥴", name: "woozy face", keywords: ["dizzy", "intoxicated"] },
    { symbol: "😵‍💫", name: "face with spiral eyes", keywords: ["dizzy", "hypnotized"] },
    { symbol: "🤯", name: "exploding head", keywords: ["mind blown", "shocked"] },
    { symbol: "🤠", name: "cowboy hat face", keywords: ["western", "yeehaw"] },
    { symbol: "🥳", name: "partying face", keywords: ["celebrate", "party"] },
    { symbol: "😈", name: "smiling face with horns", keywords: ["devil", "evil"] },
    { symbol: "👿", name: "angry face with horns", keywords: ["devil", "mad"] },
    { symbol: "👹", name: "ogre", keywords: ["monster", "japanese"] },
    { symbol: "👺", name: "goblin", keywords: ["monster", "japanese"] },
    { symbol: "🤡", name: "clown face", keywords: ["funny", "scary"] },
    { symbol: "👻", name: "ghost", keywords: ["halloween", "scary"] },
    { symbol: "👽", name: "alien", keywords: ["ufo", "extraterrestrial"] },
    { symbol: "👾", name: "alien monster", keywords: ["game", "arcade"] },
    { symbol: "🤖", name: "robot", keywords: ["tech", "android"] },
    
    // Places
    { symbol: "🗽", name: "Statue of Liberty", keywords: ["new york", "freedom"] },
    { symbol: "🏰", name: "castle", keywords: ["building", "history"] },
    { symbol: "🏯", name: "Japanese castle", keywords: ["building", "history"] },
    { symbol: "🗼", name: "Tokyo Tower", keywords: ["japan", "landmark"] },
    { symbol: "🏟️", name: "stadium", keywords: ["sports", "venue"] },
    { symbol: "🎡", name: "ferris wheel", keywords: ["amusement park", "fun"] },
    { symbol: "🎢", name: "roller coaster", keywords: ["amusement park", "thrill"] },
    { symbol: "🎠", name: "carousel horse", keywords: ["amusement park", "ride"] },
    { symbol: "⛲", name: "fountain", keywords: ["water", "park"] },
    { symbol: "⛱️", name: "umbrella on ground", keywords: ["beach", "vacation"] },
    { symbol: "🏖️", name: "beach with umbrella", keywords: ["sand", "summer"] },
    { symbol: "🏝️", name: "desert island", keywords: ["tropical", "vacation"] },
    { symbol: "🏜️", name: "desert", keywords: ["sand", "arid"] },
    { symbol: "🌋", name: "volcano", keywords: ["eruption", "mountain"] },
    { symbol: "🗾", name: "map of Japan", keywords: ["japan", "country"] },
    { symbol: "🏕️", name: "camping", keywords: ["outdoors", "tent"] },
    { symbol: "🏗️", name: "building construction", keywords: ["construction", "work"] },
    { symbol: "🏭", name: "factory", keywords: ["industry", "work"] },
    { symbol: "🏢", name: "office building", keywords: ["work", "business"] },
    { symbol: "🏬", name: "department store", keywords: ["shopping", "mall"] },
    { symbol: "🏣", name: "Japanese post office", keywords: ["mail", "japan"] },
    { symbol: "🏤", name: "post office", keywords: ["mail", "shipping"] },
    { symbol: "🏥", name: "hospital", keywords: ["health", "doctor"] },
    { symbol: "🏦", name: "bank", keywords: ["money", "business"] },
    { symbol: "🏨", name: "hotel", keywords: ["accommodation", "travel"] },
    { symbol: "🏪", name: "convenience store", keywords: ["shop", "24/7"] },
    { symbol: "🏫", name: "school", keywords: ["education", "learning"] },
    { symbol: "🏩", name: "love hotel", keywords: ["romance", "couple"] },
    { symbol: "💒", name: "wedding", keywords: ["marriage", "ceremony"] },
    { symbol: "⛪", name: "church", keywords: ["religion", "christian"] },
    { symbol: "🕌", name: "mosque", keywords: ["islam", "religion"] },
    { symbol: "🛕", name: "hindu temple", keywords: ["religion", "india"] },
    { symbol: "🕍", name: "synagogue", keywords: ["judaism", "religion"] },
    { symbol: "⛩️", name: "shinto shrine", keywords: ["japan", "religion"] },
    { symbol: "🕋", name: "kaaba", keywords: ["islam", "mecca"] },
    { symbol: "🌠", name: "shooting star", keywords: ["night", "wish"] },
    { symbol: "🌌", name: "milky way", keywords: ["space", "stars"] },
    { symbol: "⛺", name: "tent", keywords: ["camping", "outdoors"] },
    { symbol: "🌁", name: "foggy", keywords: ["weather", "mist"] },
    { symbol: "🌃", name: "night with stars", keywords: ["city", "evening"] },
    { symbol: "🏙️", name: "cityscape", keywords: ["urban", "buildings"] },
    { symbol: "🌄", name: "sunrise over mountains", keywords: ["morning", "view"] },
    { symbol: "🌅", name: "sunrise", keywords: ["morning", "beach"] },
    { symbol: "🌆", name: "cityscape at dusk", keywords: ["evening", "buildings"] },
    { symbol: "🌇", name: "sunset", keywords: ["evening", "sky"] },
    { symbol: "🌉", name: "bridge at night", keywords: ["city", "river"] },
    { symbol: "♨️", name: "hot springs", keywords: ["relax", "onsen"] },
    { symbol: "🎠", name: "carousel horse", keywords: ["amusement park", "ride"] },
    { symbol: "🎪", name: "circus tent", keywords: ["entertainment", "show"] },
    { symbol: "🚂", name: "locomotive", keywords: ["train", "transport"] },
    { symbol: "🚃", name: "railway car", keywords: ["train", "transport"] },
    { symbol: "🚄", name: "high-speed train", keywords: ["fast", "transport"] },
    { symbol: "🚅", name: "bullet train", keywords: ["fast", "japan"] },
    { symbol: "🚆", name: "train", keywords: ["transport", "travel"] },
    { symbol: "🚇", name: "metro", keywords: ["subway", "transport"] },
    { symbol: "🚈", name: "light rail", keywords: ["transport", "city"] },
    { symbol: "🚉", name: "station", keywords: ["train", "transport"] },
    { symbol: "🚊", name: "tram", keywords: ["transport", "city"] },
    { symbol: "🚝", name: "monorail", keywords: ["transport", "city"] },
    { symbol: "🚞", name: "mountain railway", keywords: ["transport", "scenic"] },
    { symbol: "🚋", name: "tram car", keywords: ["transport", "city"] },
    { symbol: "🚌", name: "bus", keywords: ["transport", "vehicle"] },
    { symbol: "🚍", name: "oncoming bus", keywords: ["transport", "vehicle"] },
    { symbol: "🚎", name: "trolleybus", keywords: ["transport", "electric"] },
    { symbol: "🚐", name: "minibus", keywords: ["transport", "vehicle"] },
    { symbol: "🚑", name: "ambulance", keywords: ["health", "emergency"] },
    { symbol: "🚒", name: "fire engine", keywords: ["fire", "emergency"] },
    { symbol: "🚓", name: "police car", keywords: ["law", "enforcement"] },
    { symbol: "🚔", name: "oncoming police car", keywords: ["law", "enforcement"] },
    { symbol: "🚕", name: "taxi", keywords: ["transport", "vehicle"] },
    { symbol: "🚖", name: "oncoming taxi", keywords: ["transport", "vehicle"] },
    { symbol: "🚗", name: "automobile", keywords: ["car", "transport"] },
    { symbol: "🚘", name: "oncoming automobile", keywords: ["car", "transport"] },
    { symbol: "🚙", name: "sport utility vehicle", keywords: ["car", "transport"] },
    { symbol: "🚚", name: "delivery truck", keywords: ["transport", "shipping"] },
    { symbol: "🚛", name: "articulated lorry", keywords: ["truck", "transport"] },
    { symbol: "🚜", name: "tractor", keywords: ["farm", "vehicle"] },
    { symbol: "🏎️", name: "racing car", keywords: ["sports", "fast"] },
    { symbol: "🏍️", name: "motorcycle", keywords: ["vehicle", "transport"] },
    { symbol: "🛵", name: "motor scooter", keywords: ["vehicle", "transport"] },
    { symbol: "🦽", name: "manual wheelchair", keywords: ["disability", "accessibility"] },
    { symbol: "🦼", name: "motorized wheelchair", keywords: ["disability", "accessibility"] },
    { symbol: "🛺", name: "auto rickshaw", keywords: ["transport", "vehicle"] },
    { symbol: "🚲", name: "bicycle", keywords: ["bike", "transport"] },
    { symbol: "🛴", name: "kick scooter", keywords: ["transport", "vehicle"] },
    { symbol: "🛹", name: "skateboard", keywords: ["sports", "transport"] },
    { symbol: "🚏", name: "bus stop", keywords: ["transport", "waiting"] },
    { symbol: "🛣️", name: "motorway", keywords: ["road", "highway"] },
    { symbol: "🛤️", name: "railway track", keywords: ["train", "transport"] },
    { symbol: "🛢️", name: "oil drum", keywords: ["fuel", "petroleum"] },
    { symbol: "⛽", name: "fuel pump", keywords: ["gas", "station"] },
    { symbol: "🚨", name: "police car light", keywords: ["emergency", "alert"] },
    { symbol: "🚥", name: "horizontal traffic light", keywords: ["signal", "stop"] },
    { symbol: "🚦", name: "vertical traffic light", keywords: ["signal", "stop"] },
    { symbol: "🛑", name: "stop sign", keywords: ["road", "stop"] },
    { symbol: "🚧", name: "construction", keywords: ["work", "progress"] },
    { symbol: "⚓", name: "anchor", keywords: ["ship", "marine"] },
    { symbol: "⛵", name: "sailboat", keywords: ["boat", "transport"] },
    { symbol: "🛶", name: "canoe", keywords: ["boat", "transport"] },
    { symbol: "🚤", name: "speedboat", keywords: ["boat", "fast"] },
    { symbol: "🛳️", name: "passenger ship", keywords: ["cruise", "transport"] },
    { symbol: "⛴️", name: "ferry", keywords: ["boat", "transport"] },
    { symbol: "🛥️", name: "motor boat", keywords: ["boat", "transport"] },
    { symbol: "🚢", name: "ship", keywords: ["transport", "marine"] },
    { symbol: "✈️", name: "airplane", keywords: ["flight", "transport"] },
    { symbol: "🛩️", name: "small airplane", keywords: ["flight", "transport"] },
    { symbol: "🛫", name: "airplane departure", keywords: ["flight", "takeoff"] },
    { symbol: "🛬", name: "airplane arrival", keywords: ["flight", "landing"] },
    { symbol: "🪂", name: "parachute", keywords: ["sky", "jump"] },
    { symbol: "💺", name: "seat", keywords: ["airplane", "transport"] },
    { symbol: "🚁", name: "helicopter", keywords: ["transport", "fly"] },
    { symbol: "🚟", name: "suspension railway", keywords: ["transport", "vehicle"] },
    { symbol: "🚠", name: "mountain cableway", keywords: ["transport", "vehicle"] },
    { symbol: "🚡", name: "aerial tramway", keywords: ["transport", "vehicle"] },
    { symbol: "🛰️", name: "satellite", keywords: ["communication", "space"] },
    { symbol: "🚀", name: "rocket", keywords: ["space", "launch"] },
    { symbol: "🛸", name: "flying saucer", keywords: ["ufo", "alien"] },
    { symbol: "🛎️", name: "bellhop bell", keywords: ["hotel", "service"] },
    { symbol: "🧳", name: "luggage", keywords: ["travel", "packing"] },
    { symbol: "⌛", name: "hourglass done", keywords: ["time", "clock"] },
    { symbol: "⏳", name: "hourglass not done", keywords: ["time", "clock"] },
    { symbol: "⌚", name: "watch", keywords: ["time", "accessory"] },
    { symbol: "⏰", name: "alarm clock", keywords: ["time", "wake"] },
    { symbol: "⏱️", name: "stopwatch", keywords: ["time", "sports"] },
    { symbol: "⏲️", name: "timer clock", keywords: ["time", "cooking"] },
    { symbol: "🕰️", name: "mantelpiece clock", keywords: ["time", "decor"] },
    { symbol: "🕛", name: "twelve o'clock", keywords: ["time", "12"] },
    { symbol: "🕧", name: "twelve-thirty", keywords: ["time", "12:30"] },
    { symbol: "🕐", name: "one o'clock", keywords: ["time", "1"] },
    { symbol: "🕜", name: "one-thirty", keywords: ["time", "1:30"] },
    { symbol: "🕑", name: "two o'clock", keywords: ["time", "2"] },
    { symbol: "🕝", name: "two-thirty", keywords: ["time", "2:30"] },
    { symbol: "🕒", name: "three o'clock", keywords: ["time", "3"] },
    { symbol: "🕞", name: "three-thirty", keywords: ["time", "3:30"] },
    { symbol: "🕓", name: "four o'clock", keywords: ["time", "4"] },
    { symbol: "🕟", name: "four-thirty", keywords: ["time", "4:30"] },
    { symbol: "🕔", name: "five o'clock", keywords: ["time", "5"] },
    { symbol: "🕠", name: "five-thirty", keywords: ["time", "5:30"] },
    { symbol: "🕕", name: "six o'clock", keywords: ["time", "6"] },
    { symbol: "🕡", name: "six-thirty", keywords: ["time", "6:30"] },
    { symbol: "🕖", name: "seven o'clock", keywords: ["time", "7"] },
    { symbol: "🕢", name: "seven-thirty", keywords: ["time", "7:30"] },
    { symbol: "🕗", name: "eight o'clock", keywords: ["time", "8"] },
    { symbol: "🕣", name: "eight-thirty", keywords: ["time", "8:30"] },
    { symbol: "🕘", name: "nine o'clock", keywords: ["time", "9"] },
    { symbol: "🕤", name: "nine-thirty", keywords: ["time", "9:30"] },
    { symbol: "🕙", name: "ten o'clock", keywords: ["time", "10"] },
    { symbol: "🕥", name: "ten-thirty", keywords: ["time", "10:30"] },
    { symbol: "🕚", name: "eleven o'clock", keywords: ["time", "11"] },
    { symbol: "🕦", name: "eleven-thirty", keywords: ["time", "11:30"] },
    { symbol: "🌑", name: "new moon", keywords: ["space", "dark"] },
    { symbol: "🌒", name: "waxing crescent moon", keywords: ["space", "growing"] },
    { symbol: "🌓", name: "first quarter moon", keywords: ["space", "half"] },
    { symbol: "🌔", name: "waxing gibbous moon", keywords: ["space", "growing"] },
    { symbol: "🌕", name: "full moon", keywords: ["space", "bright"] },
    { symbol: "🌖", name: "waning gibbous moon", keywords: ["space", "shrinking"] },
    { symbol: "🌗", name: "last quarter moon", keywords: ["space", "half"] },
    { symbol: "🌘", name: "waning crescent moon", keywords: ["space", "shrinking"] },
    { symbol: "🌙", name: "crescent moon", keywords: ["space", "night"] },
    { symbol: "🌚", name: "new moon face", keywords: ["space", "dark"] },
    { symbol: "🌛", name: "first quarter moon face", keywords: ["space", "half"] },
    { symbol: "🌜", name: "last quarter moon face", keywords: ["space", "half"] },
    { symbol: "🌡️", name: "thermometer", keywords: ["weather", "temperature"] },
    { symbol: "☀️", name: "sun", keywords: ["weather", "bright"] },
    { symbol: "🌝", name: "full moon face", keywords: ["space", "bright"] },
    { symbol: "🌞", name: "sun with face", keywords: ["weather", "happy"] },
    { symbol: "🪐", name: "ringed planet", keywords: ["saturn", "space"] },
    { symbol: "⭐", name: "star", keywords: ["night", "bright"] },
    { symbol: "🌟", name: "glowing star", keywords: ["night", "bright"] },
    { symbol: "🌠", name: "shooting star", keywords: ["night", "wish"] },
    { symbol: "🌌", name: "milky way", keywords: ["space", "stars"] },
    { symbol: "☁️", name: "cloud", keywords: ["weather", "sky"] },
    { symbol: "⛅", name: "sun behind cloud", keywords: ["weather", "partly sunny"] },
    { symbol: "⛈️", name: "cloud with lightning and rain", keywords: ["weather", "storm"] },
    { symbol: "🌤️", name: "sun behind small cloud", keywords: ["weather", "partly sunny"] },
    { symbol: "🌥️", name: "sun behind large cloud", keywords: ["weather", "partly sunny"] },
    { symbol: "🌦️", name: "sun behind rain cloud", keywords: ["weather", "rain"] },
    { symbol: "🌧️", name: "cloud with rain", keywords: ["weather", "rain"] },
    { symbol: "🌨️", name: "cloud with snow", keywords: ["weather", "winter"] },
    { symbol: "🌩️", name: "cloud with lightning", keywords: ["weather", "storm"] },
    { symbol: "🌪️", name: "tornado", keywords: ["weather", "danger"] },
    { symbol: "🌫️", name: "fog", keywords: ["weather", "mist"] },
    { symbol: "🌬️", name: "wind face", keywords: ["weather", "blow"] },
    { symbol: "🌀", name: "cyclone", keywords: ["weather", "spin"] },
    { symbol: "🌈", name: "rainbow", keywords: ["weather", "color"] },
    { symbol: "🌂", name: "closed umbrella", keywords: ["weather", "rain"] },
    { symbol: "☂️", name: "umbrella", keywords: ["weather", "rain"] },
    { symbol: "☔", name: "umbrella with rain drops", keywords: ["weather", "rain"] },
    { symbol: "⛱️", name: "umbrella on ground", keywords: ["weather", "sun"] },
    { symbol: "⚡", name: "high voltage", keywords: ["electric", "danger"] },
    { symbol: "❄️", name: "snowflake", keywords: ["weather", "winter"] },
    { symbol: "☃️", name: "snowman", keywords: ["weather", "winter"] },
    { symbol: "⛄", name: "snowman without snow", keywords: ["weather", "winter"] },
    { symbol: "☄️", name: "comet", keywords: ["space", "shooting star"] },
    { symbol: "🔥", name: "fire", keywords: ["hot", "burn"] },
    { symbol: "💧", name: "droplet", keywords: ["water", "rain"] },
    { symbol: "🌊", name: "water wave", keywords: ["ocean", "sea"] },
    { symbol: "🎃", name: "jack-o-lantern", keywords: ["halloween", "pumpkin"] },
    { symbol: "🎄", name: "Christmas tree", keywords: ["holiday", "december"] },
    { symbol: "🎆", name: "fireworks", keywords: ["celebration", "new year"] },
    { symbol: "🎇", name: "sparkler", keywords: ["celebration", "fire"] },
    { symbol: "🧨", name: "firecracker", keywords: ["celebration", "explosion"] },
    { symbol: "✨", name: "sparkles", keywords: ["shiny", "magic"] },
    { symbol: "🎈", name: "balloon", keywords: ["party", "celebration"] },
    { symbol: "🎉", name: "party popper", keywords: ["celebration", "fun"] },
    { symbol: "🎊", name: "confetti ball", keywords: ["celebration", "party"] },
    { symbol: "🎋", name: "tanabata tree", keywords: ["japan", "festival"] },
    { symbol: "🎍", name: "pine decoration", keywords: ["japan", "festival"] },
    { symbol: "🎎", name: "Japanese dolls", keywords: ["japan", "festival"] },
    { symbol: "🎏", name: "carp streamer", keywords: ["japan", "festival"] },
    { symbol: "🎐", name: "wind chime", keywords: ["japan", "festival"] },
    { symbol: "🎑", name: "moon viewing ceremony", keywords: ["japan", "festival"] },
    { symbol: "🧧", name: "red envelope", keywords: ["chinese", "new year"] },
    { symbol: "🎀", name: "ribbon", keywords: ["decoration", "gift"] },
    { symbol: "🎁", name: "wrapped gift", keywords: ["present", "birthday"] },
    { symbol: "🎗️", name: "reminder ribbon", keywords: ["awareness", "cause"] },
    { symbol: "🎟️", name: "admission tickets", keywords: ["event", "concert"] },
    { symbol: "🎫", name: "ticket", keywords: ["event", "concert"] },
    { symbol: "🎖️", name: "military medal", keywords: ["award", "honor"] },
    { symbol: "🏆", name: "trophy", keywords: ["award", "win"] },
    { symbol: "🏅", name: "sports medal", keywords: ["award", "sports"] },
    { symbol: "🥇", name: "1st place medal", keywords: ["gold", "win"] },
    { symbol: "🥈", name: "2nd place medal", keywords: ["silver", "second"] },
    { symbol: "🥉", name: "3rd place medal", keywords: ["bronze", "third"] },
    { symbol: "⚽", name: "soccer ball", keywords: ["sports", "football"] },
    { symbol: "⚾", name: "baseball", keywords: ["sports", "game"] },
    { symbol: "🥎", name: "softball", keywords: ["sports", "game"] },
    { symbol: "🏀", name: "basketball", keywords: ["sports", "game"] },
    { symbol: "🏐", name: "volleyball", keywords: ["sports", "game"] },
    { symbol: "🏈", name: "american football", keywords: ["sports", "game"] },
    { symbol: "🏉", name: "rugby football", keywords: ["sports", "game"] },
    { symbol: "🎾", name: "tennis", keywords: ["sports", "game"] },
    { symbol: "🥏", name: "flying disc", keywords: ["sports", "frisbee"] },
    { symbol: "🎳", name: "bowling", keywords: ["sports", "game"] },
    { symbol: "🏏", name: "cricket game", keywords: ["sports", "game"] },
    { symbol: "🏑", name: "field hockey", keywords: ["sports", "game"] },
    { symbol: "🏒", name: "ice hockey", keywords: ["sports", "game"] },
    { symbol: "🥍", name: "lacrosse", keywords: ["sports", "game"] },
    { symbol: "🏓", name: "ping pong", keywords: ["sports", "game"] },
    { symbol: "🏸", name: "badminton", keywords: ["sports", "game"] },
    { symbol: "🥊", name: "boxing glove", keywords: ["sports", "fight"] },
    { symbol: "🥋", name: "martial arts uniform", keywords: ["sports", "karate"] },
    { symbol: "🥅", name: "goal net", keywords: ["sports", "soccer"] },
    { symbol: "⛳", name: "flag in hole", keywords: ["sports", "golf"] },
    { symbol: "⛸️", name: "ice skate", keywords: ["sports", "winter"] },
    { symbol: "🎣", name: "fishing pole", keywords: ["sports", "hobby"] },
    { symbol: "🤿", name: "diving mask", keywords: ["sports", "scuba"] },
    { symbol: "🎽", name: "running shirt", keywords: ["sports", "marathon"] },
    { symbol: "🎿", name: "skis", keywords: ["sports", "winter"] },
    { symbol: "🛷", name: "sled", keywords: ["sports", "winter"] },
    { symbol: "🥌", name: "curling stone", keywords: ["sports", "game"] },
    { symbol: "🎯", name: "bullseye", keywords: ["game", "target"] },
    { symbol: "🪀", name: "yo-yo", keywords: ["toy", "game"] },
    { symbol: "🪁", name: "kite", keywords: ["toy", "outdoor"] },
    { symbol: "🎱", name: "pool 8 ball", keywords: ["game", "billiards"] },
    { symbol: "🔮", name: "crystal ball", keywords: ["fortune", "magic"] },
    { symbol: "🪄", name: "magic wand", keywords: ["magic", "fantasy"] },
    { symbol: "🧿", name: "nazar amulet", keywords: ["protection", "evil eye"] },
    { symbol: "🎮", name: "video game", keywords: ["game", "play"] },
    { symbol: "🕹️", name: "joystick", keywords: ["game", "play"] },
    { symbol: "🎰", name: "slot machine", keywords: ["game", "casino"] },
    { symbol: "🎲", name: "game die", keywords: ["game", "dice"] },
    { symbol: "🧩", name: "puzzle piece", keywords: ["game", "solve"] },
    { symbol: "🧸", name: "teddy bear", keywords: ["toy", "childhood"] },
    { symbol: "🪅", name: "piñata", keywords: ["party", "celebration"] },
    { symbol: "🪆", name: "nesting dolls", keywords: ["toy", "russian"] },
    { symbol: "♠️", name: "spade suit", keywords: ["card", "game"] },
    { symbol: "♥️", name: "heart suit", keywords: ["card", "game"] },
    { symbol: "♦️", name: "diamond suit", keywords: ["card", "game"] },
    { symbol: "♣️", name: "club suit", keywords: ["card", "game"] },
    { symbol: "♟️", name: "chess pawn", keywords: ["game", "strategy"] },
    { symbol: "🃏", name: "joker", keywords: ["card", "game"] },
    { symbol: "🀄", name: "mahjong red dragon", keywords: ["game", "chinese"] },
    { symbol: "🎴", name: "flower playing cards", keywords: ["game", "japanese"] },
    { symbol: "🎭", name: "performing arts", keywords: ["theater", "drama"] },
    { symbol: "🖼️", name: "framed picture", keywords: ["art", "photo"] },
    { symbol: "🎨", name: "artist palette", keywords: ["art", "paint"] },
    { symbol: "🧵", name: "thread", keywords: ["sewing", "needle"] },
    { symbol: "🪡", name: "sewing needle", keywords: ["sewing", "thread"] },
    { symbol: "🧶", name: "yarn", keywords: ["knitting", "wool"] },
    { symbol: "🪢", name: "knot", keywords: ["rope", "tie"] },
    { symbol: "👓", name: "glasses", keywords: ["vision", "eyewear"] },
    { symbol: "🕶️", name: "sunglasses", keywords: ["sun", "eyewear"] },
    { symbol: "🥽", name: "goggles", keywords: ["safety", "swim"] },
    { symbol: "🥼", name: "lab coat", keywords: ["science", "doctor"] },
    { symbol: "🦺", name: "safety vest", keywords: ["construction", "safety"] },
    { symbol: "👔", name: "necktie", keywords: ["shirt", "formal"] },
    { symbol: "👕", name: "t-shirt", keywords: ["shirt", "clothing"] },
    { symbol: "👖", name: "jeans", keywords: ["pants", "clothing"] },
    { symbol: "🧣", name: "scarf", keywords: ["winter", "clothing"] },
    { symbol: "🧤", name: "gloves", keywords: ["winter", "clothing"] },
    { symbol: "🧥", name: "coat", keywords: ["winter", "clothing"] },
    { symbol: "🧦", name: "socks", keywords: ["clothing", "feet"] },
    { symbol: "👗", name: "dress", keywords: ["clothing", "fashion"] },
    { symbol: "👘", name: "kimono", keywords: ["japanese", "clothing"] },
    { symbol: "🥻", name: "sari", keywords: ["indian", "clothing"] },
    { symbol: "🩱", name: "one-piece swimsuit", keywords: ["swim", "clothing"] },
    { symbol: "🩲", name: "briefs", keywords: ["underwear", "clothing"] },
    { symbol: "🩳", name: "shorts", keywords: ["clothing", "summer"] },
    { symbol: "👙", name: "bikini", keywords: ["swim", "beach"] },
    { symbol: "👚", name: "woman's clothes", keywords: ["fashion", "clothing"] },
    { symbol: "👛", name: "purse", keywords: ["money", "accessory"] },
    { symbol: "👜", name: "handbag", keywords: ["bag", "accessory"] },
    { symbol: "👝", name: "clutch bag", keywords: ["bag", "accessory"] },
    { symbol: "🛍️", name: "shopping bags", keywords: ["shopping", "bags"] },
    { symbol: "🎒", name: "backpack", keywords: ["school", "bag"] },
    { symbol: "🩴", name: "thong sandal", keywords: ["footwear", "summer"] },
    { symbol: "👞", name: "man's shoe", keywords: ["footwear", "formal"] },
    { symbol: "👟", name: "running shoe", keywords: ["sports", "footwear"] },
    { symbol: "🥾", name: "hiking boot", keywords: ["outdoor", "footwear"] },
    { symbol: "🥿", name: "flat shoe", keywords: ["footwear", "comfortable"] },
    { symbol: "👠", name: "high-heeled shoe", keywords: ["footwear", "fashion"] },
    { symbol: "👡", name: "woman's sandal", keywords: ["footwear", "summer"] },
    { symbol: "🩰", name: "ballet shoes", keywords: ["dance", "footwear"] },
    { symbol: "👢", name: "woman's boot", keywords: ["footwear", "winter"] },
    { symbol: "👑", name: "crown", keywords: ["royalty", "king"] },
    { symbol: "👒", name: "woman's hat", keywords: ["fashion", "accessory"] },
    { symbol: "🎩", name: "top hat", keywords: ["formal", "magic"] },
    { symbol: "🎓", name: "graduation cap", keywords: ["school", "degree"] },
    { symbol: "🧢", name: "billed cap", keywords: ["hat", "casual"] },
    { symbol: "🪖", name: "military helmet", keywords: ["army", "safety"] },
    { symbol: "⛑️", name: "rescue worker's helmet", keywords: ["safety", "emergency"] },
    { symbol: "📿", name: "prayer beads", keywords: ["religion", "pray"] },
    { symbol: "💄", name: "lipstick", keywords: ["makeup", "beauty"] },
    { symbol: "💍", name: "ring", keywords: ["jewelry", "wedding"] },
    { symbol: "💎", name: "gem stone", keywords: ["jewelry", "diamond"] },
    { symbol: "🔇", name: "muted speaker", keywords: ["sound", "silent"] },
    { symbol: "🔈", name: "speaker low volume", keywords: ["sound", "quiet"] },
    { symbol: "🔉", name: "speaker medium volume", keywords: ["sound", "volume"] },
    { symbol: "🔊", name: "speaker high volume", keywords: ["sound", "loud"] },
    { symbol: "📢", name: "loudspeaker", keywords: ["announcement", "sound"] },
    { symbol: "📣", name: "megaphone", keywords: ["announcement", "sound"] },
    { symbol: "📯", name: "postal horn", keywords: ["mail", "sound"] },
    { symbol: "🔔", name: "bell", keywords: ["sound", "notification"] },
    { symbol: "🔕", name: "bell with slash", keywords: ["silent", "no sound"] },
    { symbol: "🎼", name: "musical score", keywords: ["music", "sheet"] },
    { symbol: "🎵", name: "musical note", keywords: ["music", "sound"] },
    { symbol: "🎶", name: "musical notes", keywords: ["music", "sound"] },
    { symbol: "🎙️", name: "studio microphone", keywords: ["music", "recording"] },
    { symbol: "🎚️", name: "level slider", keywords: ["music", "sound"] },
    { symbol: "🎛️", name: "control knobs", keywords: ["music", "sound"] },
    { symbol: "🎤", name: "microphone", keywords: ["music", "sing"] },
    { symbol: "🎧", name: "headphone", keywords: ["music", "sound"] },
    { symbol: "📻", name: "radio", keywords: ["music", "sound"] },
    { symbol: "🎷", name: "saxophone", keywords: ["music", "instrument"] },
    { symbol: "🪗", name: "accordion", keywords: ["music", "instrument"] },
    { symbol: "🎸", name: "guitar", keywords: ["music", "instrument"] },
    { symbol: "🎹", name: "musical keyboard", keywords: ["music", "piano"] },
    { symbol: "🎺", name: "trumpet", keywords: ["music", "instrument"] },
    { symbol: "🎻", name: "violin", keywords: ["music", "instrument"] },
    { symbol: "🪕", name: "banjo", keywords: ["music", "instrument"] },
    { symbol: "🥁", name: "drum", keywords: ["music", "instrument"] },
    { symbol: "🪘", name: "long drum", keywords: ["music", "instrument"] },
    { symbol: "📱", name: "mobile phone", keywords: ["smartphone", "tech"] },
    { symbol: "📲", name: "mobile phone with arrow", keywords: ["call", "text"] },
    { symbol: "☎️", name: "telephone", keywords: ["call", "phone"] },
    { symbol: "📞", name: "telephone receiver", keywords: ["call", "phone"] },
    { symbol: "📟", name: "pager", keywords: ["communication", "old"] },
    { symbol: "📠", name: "fax machine", keywords: ["communication", "office"] },
    { symbol: "🔋", name: "battery", keywords: ["power", "energy"] },
    { symbol: "🔌", name: "electric plug", keywords: ["power", "electricity"] },
    { symbol: "💻", name: "laptop", keywords: ["computer", "tech"] },
    { symbol: "🖥️", name: "desktop computer", keywords: ["computer", "tech"] },
    { symbol: "🖨️", name: "printer", keywords: ["office", "tech"] },
    { symbol: "⌨️", name: "keyboard", keywords: ["computer", "type"] },
    { symbol: "🖱️", name: "computer mouse", keywords: ["computer", "tech"] },
    { symbol: "🖲️", name: "trackball", keywords: ["computer", "tech"] },
    { symbol: "💽", name: "computer disk", keywords: ["tech", "old"] },
    { symbol: "💾", name: "floppy disk", keywords: ["save", "old"] },
    { symbol: "💿", name: "optical disk", keywords: ["cd", "dvd"] },
    { symbol: "📀", name: "dvd", keywords: ["movie", "disk"] },
    { symbol: "🧮", name: "abacus", keywords: ["calculate", "old"] },
    { symbol: "🎥", name: "movie camera", keywords: ["film", "video"] },
    { symbol: "🎞️", name: "film frames", keywords: ["movie", "film"] },
    { symbol: "📽️", name: "film projector", keywords: ["movie", "film"] },
    { symbol: "🎬", name: "clapper board", keywords: ["movie", "film"] },
    { symbol: "📺", name: "television", keywords: ["tv", "show"] },
    { symbol: "📷", name: "camera", keywords: ["photo", "picture"] },
    { symbol: "📸", name: "camera with flash", keywords: ["photo", "picture"] },
    { symbol: "📹", name: "video camera", keywords: ["film", "record"] },
    { symbol: "📼", name: "videocassette", keywords: ["video", "old"] },
    { symbol: "🔍", name: "magnifying glass tilted left", keywords: ["search", "zoom"] },
    { symbol: "🔎", name: "magnifying glass tilted right", keywords: ["search", "zoom"] },
    { symbol: "🕯️", name: "candle", keywords: ["light", "romantic"] },
    { symbol: "💡", name: "light bulb", keywords: ["idea", "bright"] },
    { symbol: "🔦", name: "flashlight", keywords: ["light", "dark"] },
    { symbol: "🏮", name: "red paper lantern", keywords: ["light", "japanese"] },
    { symbol: "🪔", name: "diya lamp", keywords: ["light", "indian"] },
    { symbol: "📔", name: "notebook with decorative cover", keywords: ["book", "notes"] },
    { symbol: "📕", name: "closed book", keywords: ["book", "read"] },
    { symbol: "📖", name: "open book", keywords: ["book", "read"] },
    { symbol: "📗", name: "green book", keywords: ["book", "read"] },
    { symbol: "📘", name: "blue book", keywords: ["book", "read"] },
    { symbol: "📙", name: "orange book", keywords: ["book", "read"] },
    { symbol: "📚", name: "books", keywords: ["library", "read"] },
    { symbol: "📓", name: "notebook", keywords: ["notes", "write"] },
    { symbol: "📒", name: "ledger", keywords: ["notes", "accounting"] },
    { symbol: "📃", name: "page with curl", keywords: ["document", "paper"] },
    { symbol: "📜", name: "scroll", keywords: ["document", "old"] },
    { symbol: "📄", name: "page facing up", keywords: ["document", "paper"] },
    { symbol: "📰", name: "newspaper", keywords: ["news", "read"] },
    { symbol: "🗞️", name: "rolled-up newspaper", keywords: ["news", "read"] },
    { symbol: "📑", name: "bookmark tabs", keywords: ["bookmark", "organize"] },
    { symbol: "🔖", name: "bookmark", keywords: ["save", "read"] },
    { symbol: "🏷️", name: "label", keywords: ["tag", "price"] },
    { symbol: "💰", name: "money bag", keywords: ["dollar", "rich"] },
    { symbol: "🪙", name: "coin", keywords: ["money", "currency"] },
    { symbol: "💴", name: "yen banknote", keywords: ["money", "japanese"] },
    { symbol: "💵", name: "dollar banknote", keywords: ["money", "currency"] },
    { symbol: "💶", name: "euro banknote", keywords: ["money", "currency"] },
    { symbol: "💷", name: "pound banknote", keywords: ["money", "currency"] },
    { symbol: "💸", name: "money with wings", keywords: ["dollar", "spend"] },
    { symbol: "💳", name: "credit card", keywords: ["money", "payment"] },
    { symbol: "🧾", name: "receipt", keywords: ["money", "proof"] },
    { symbol: "💹", name: "chart increasing with yen", keywords: ["money", "growth"] },
    { symbol: "✉️", name: "envelope", keywords: ["letter", "mail"] },
    { symbol: "📧", name: "e-mail", keywords: ["email", "communication"] },
    { symbol: "📨", name: "incoming envelope", keywords: ["mail", "letter"] },
    { symbol: "📩", name: "envelope with arrow", keywords: ["mail", "send"] },
    { symbol: "📤", name: "outbox tray", keywords: ["mail", "send"] },
    { symbol: "📥", name: "inbox tray", keywords: ["mail", "receive"] },
    { symbol: "📦", name: "package", keywords: ["mail", "delivery"] },
    { symbol: "📫", name: "closed mailbox with raised flag", keywords: ["mail", "letter"] },
    { symbol: "📪", name: "closed mailbox with lowered flag", keywords: ["mail", "letter"] },
    { symbol: "📬", name: "open mailbox with raised flag", keywords: ["mail", "letter"] },
    { symbol: "📭", name: "open mailbox with lowered flag", keywords: ["mail", "letter"] },
    { symbol: "📮", name: "postbox", keywords: ["mail", "letter"] },
    { symbol: "🗳️", name: "ballot box with ballot", keywords: ["vote", "election"] },
    { symbol: "✏️", name: "pencil", keywords: ["write", "draw"] },
    { symbol: "✒️", name: "black nib", keywords: ["pen", "write"] },
    { symbol: "🖋️", name: "fountain pen", keywords: ["pen", "write"] },
    { symbol: "🖊️", name: "pen", keywords: ["write", "draw"] },
    { symbol: "🖌️", name: "paintbrush", keywords: ["art", "draw"] },
    { symbol: "🖍️", name: "crayon", keywords: ["art", "draw"] },
    { symbol: "📝", name: "memo", keywords: ["write", "notes"] },
    { symbol: "💼", name: "briefcase", keywords: ["work", "business"] },
    { symbol: "📁", name: "file folder", keywords: ["documents", "organize"] },
    { symbol: "📂", name: "open file folder", keywords: ["documents", "organize"] },
    { symbol: "🗂️", name: "card index dividers", keywords: ["organize", "files"] },
    { symbol: "📅", name: "calendar", keywords: ["schedule", "date"] },
    { symbol: "📆", name: "tear-off calendar", keywords: ["schedule", "date"] },
    { symbol: "🗒️", name: "spiral notepad", keywords: ["notes", "write"] },
    { symbol: "🗓️", name: "spiral calendar", keywords: ["schedule", "date"] },
    { symbol: "📇", name: "card index", keywords: ["organize", "files"] },
    { symbol: "📈", name: "chart increasing", keywords: ["graph", "growth"] },
    { symbol: "📉", name: "chart decreasing", keywords: ["graph", "decline"] },
    { symbol: "📊", name: "bar chart", keywords: ["graph", "stats"] },
    { symbol: "📋", name: "clipboard", keywords: ["notes", "copy"] },
    { symbol: "📌", name: "pushpin", keywords: ["pin", "attach"] },
    { symbol: "📍", name: "round pushpin", keywords: ["pin", "location"] },
    { symbol: "📎", name: "paperclip", keywords: ["attach", "file"] },
    { symbol: "🖇️", name: "linked paperclips", keywords: ["attach", "files"] },
    { symbol: "📏", name: "straight ruler", keywords: ["measure", "length"] },
    { symbol: "📐", name: "triangular ruler", keywords: ["measure", "math"] },
    { symbol: "✂️", name: "scissors", keywords: ["cut", "tool"] },
    { symbol: "🗃️", name: "card file box", keywords: ["organize", "files"] },
    { symbol: "🗄️", name: "file cabinet", keywords: ["organize", "files"] },
    { symbol: "🗑️", name: "wastebasket", keywords: ["trash", "delete"] },
    { symbol: "🔒", name: "locked", keywords: ["security", "private"] },
    { symbol: "🔓", name: "unlocked", keywords: ["security", "open"] },
    { symbol: "🔏", name: "locked with pen", keywords: ["security", "private"] },
    { symbol: "🔐", name: "locked with key", keywords: ["security", "private"] },
    { symbol: "🔑", name: "key", keywords: ["lock", "security"] },
    { symbol: "🗝️", name: "old key", keywords: ["lock", "security"] },
    { symbol: "🔨", name: "hammer", keywords: ["tool", "build"] },
    { symbol: "🪓", name: "axe", keywords: ["tool", "chop"] },
    { symbol: "⛏️", name: "pick", keywords: ["tool", "mine"] },
    { symbol: "⚒️", name: "hammer and pick", keywords: ["tools", "build"] },
    { symbol: "🛠️", name: "hammer and wrench", keywords: ["tools", "build"] },
    { symbol: "🗡️", name: "dagger", keywords: ["weapon", "knife"] },
    { symbol: "⚔️", name: "crossed swords", keywords: ["weapon", "battle"] },
    { symbol: "🔫", name: "pistol", keywords: ["weapon", "gun"] },
    { symbol: "🪃", name: "boomerang", keywords: ["weapon", "australia"] },
    { symbol: "🏹", name: "bow and arrow", keywords: ["weapon", "hunt"] },
    { symbol: "🛡️", name: "shield", keywords: ["protection", "defense"] },
    { symbol: "🪚", name: "carpentry saw", keywords: ["tool", "cut"] },
    { symbol: "🔧", name: "wrench", keywords: ["tool", "fix"] },
    { symbol: "🪛", name: "screwdriver", keywords: ["tool", "fix"] },
    { symbol: "🔩", name: "nut and bolt", keywords: ["tool", "fix"] },
    { symbol: "⚙️", name: "gear", keywords: ["tool", "mechanical"] },
    { symbol: "🗜️", name: "clamp", keywords: ["tool", "hold"] },
    { symbol: "⚖️", name: "balance scale", keywords: ["justice", "law"] },
    { symbol: "🦯", name: "white cane", keywords: ["blind", "accessibility"] },
    { symbol: "🔗", name: "link", keywords: ["connect", "url"] },
    { symbol: "⛓️", name: "chains", keywords: ["connect", "restrain"] },
    { symbol: "🪝", name: "hook", keywords: ["tool", "catch"] },
    { symbol: "🧰", name: "toolbox", keywords: ["tools", "fix"] },
    { symbol: "🧲", name: "magnet", keywords: ["attract", "metal"] },
    { symbol: "🪜", name: "ladder", keywords: ["tool", "climb"] },
    { symbol: "⚗️", name: "alembic", keywords: ["science", "chemistry"] },
    { symbol: "🧪", name: "test tube", keywords: ["science", "chemistry"] },
    { symbol: "🧫", name: "petri dish", keywords: ["science", "bacteria"] },
    { symbol: "🧬", name: "dna", keywords: ["science", "biology"] },
    { symbol: "🔬", name: "microscope", keywords: ["science", "research"] },
    { symbol: "🔭", name: "telescope", keywords: ["science", "space"] },
    { symbol: "📡", name: "satellite antenna", keywords: ["communication", "signal"] },
    { symbol: "💉", name: "syringe", keywords: ["health", "medicine"] },
    { symbol: "🩸", name: "drop of blood", keywords: ["health", "medicine"] },
    { symbol: "💊", name: "pill", keywords: ["health", "medicine"] },
    { symbol: "🩹", name: "adhesive bandage", keywords: ["health", "injury"] },
    { symbol: "🩼", name: "crutch", keywords: ["health", "injury"] },
    { symbol: "🩺", name: "stethoscope", keywords: ["health", "doctor"] },
    { symbol: "🩻", name: "x-ray", keywords: ["health", "scan"] },
    { symbol: "🚪", name: "door", keywords: ["entry", "exit"] },
    { symbol: "🛗", name: "elevator", keywords: ["lift", "building"] },
    { symbol: "🪞", name: "mirror", keywords: ["reflection", "look"] },
    { symbol: "🪟", name: "window", keywords: ["view", "outside"] },
    { symbol: "🛏️", name: "bed", keywords: ["sleep", "rest"] },
    { symbol: "🛋️", name: "couch and lamp", keywords: ["furniture", "living room"] },
    { symbol: "🪑", name: "chair", keywords: ["furniture", "sit"] },
    { symbol: "🚽", name: "toilet", keywords: ["bathroom", "restroom"] },
    { symbol: "🪠", name: "plunger", keywords: ["toilet", "clog"] },
]